MAX_PIXEL_VALUE = 65535
BUCKET_NAME = "cindy-profiling"
RAW_BASE_PATH = "TargetActivationAdvanced/"
CLEAN_BASE_PATH = "Data/"
RUNS_BASE_PATH = "Runs/"

IMAGE_HEIGHT = 64
IMAGE_WIDTH = 64
NUM_WORKERS = 2
BATCH_SIZE = 8
FEATURES = [32, 64] #[64, 128, 256, 512]
LEARNING_RATE = 1e-4
NUM_EPOCHS = 1

SAVE_STATS = True
