MAX_PIXEL_VALUE = 65535
BUCKET_NAME = "cindy-profiling"
RAW_BASE_PATH = "TargetActivationAdvanced/"
CLEAN_BASE_PATH = "Data/"

IMAGE_HEIGHT = 512
IMAGE_WIDTH = 512
NUM_WORKERS = 2
BATCH_SIZE = 16
LEARNING_RATE = 1e-4
NUM_EPOCHS = 1